# Generated by Django 3.2.5 on 2021-07-15 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appCodingNote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='created_at',
            new_name='folder_created_at',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='updated_at',
            new_name='folder_updated_at',
        ),
        migrations.AddField(
            model_name='folder',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=256)),
                ('note_link', models.URLField()),
                ('note_link_title', models.CharField(max_length=256)),
                ('note_comment', models.TextField()),
                ('note_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note_updated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bookmark_users', models.ManyToManyField(blank=True, related_name='bookmark_notes', through='appCodingNote.Bookmark', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='appCodingNote.folder')),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCodingNote.note'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
