# Generated by Django 3.2.5 on 2021-07-19 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appCodingNote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_link_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='note',
            name='tag_users',
            field=models.ManyToManyField(blank=True, related_name='tag_notes', through='appCodingNote.Tag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_link_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
