# Generated by Django 3.2.5 on 2021-07-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodingNote', '0002_auto_20210719_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_link_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
