# Generated by Django 3.2.5 on 2021-07-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodingNote', '0003_alter_note_note_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
