# Generated by Django 3.2.5 on 2021-07-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodingNote', '0004_alter_note_note_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag_users',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='note',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='appCodingNote.Tag'),
        ),
    ]
