# Generated by Django 3.2.5 on 2021-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodingNote', '0006_auto_20210724_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
