
# Generated by Django 3.2.5 on 2021-07-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCodingNote', '0007_alter_note_note_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_overflow_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
